"""Focused publication form; browser controls are grouped in an optional section."""
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QGridLayout, QLineEdit,
                            QTextEdit, QCheckBox, QComboBox, QDoubleSpinBox, QTabWidget,
                            QMenu, QToolButton)
from desktop_theme import button, card, fold, label, scroll_content


def build(tab):
    outer = QVBoxLayout(tab)
    outer.setContentsMargins(26, 22, 26, 20)
    outer.setSpacing(16)
    outer.addWidget(label('发布准备', 'heading'))
    outer.addWidget(label('选择成品与本家资料，检查标题、封面和简介。上传后在网页确认发布。', 'muted'))
    content = scroll_content(outer)
    tab.form_panel = content
    grid = QGridLayout(content)
    grid.setContentsMargins(0, 0, 0, 0)
    grid.setSpacing(18)
    grid.setColumnStretch(0, 2)
    grid.setColumnStretch(1, 3)
    left, right = QVBoxLayout(), QVBoxLayout()
    left.setSpacing(18)
    right.setSpacing(18)
    grid.addLayout(left, 0, 0)
    grid.addLayout(right, 0, 1)
    source, body = card('成品与来源', '本家、STAFF 与原始封面来自所选来源任务。', '01')
    tab.job = QLineEdit()
    tab.job.setReadOnly(True)
    tab.job.setPlaceholderText('选择来源任务')
    tab.row(body, '来源', tab.job, '选择', tab.choose_job)
    body.addWidget(button('使用当前 MIDI 任务', tab.current_job))
    tab.bv = QLineEdit()
    tab.bv.setPlaceholderText('或粘贴本家 BV 号 / 链接')
    body.addWidget(tab.bv)
    tab.fetch = button('读取本家资料', tab.fetch_source)
    body.addWidget(tab.fetch)
    tab.source_info = label('先选择来源，确保封面和简介对应同一首歌。', 'muted')
    body.addWidget(tab.source_info)
    tab.video = QLineEdit()
    tab.video.setPlaceholderText('调音与剪辑完成的视频')
    tab.row(body, '成品', tab.video, '选择', tab.choose_video)
    left.addWidget(source)
    cover, body = card('视频封面', '默认使用本家在 B站展示的原始封面。', '02')
    tab.cover_mode = QComboBox()
    tab.cover_mode.addItem('本家原始封面', 'original')
    tab.cover_mode.addItem('视频画面截图', 'frame')
    tab.cover_mode.addItem('自选图片', 'custom')
    body.addWidget(tab.cover_mode)
    tab.cover_seconds = QDoubleSpinBox()
    tab.cover_seconds.setRange(0, 86400)
    tab.cover_seconds.setDecimals(2)
    tab.cover_seconds.setValue(20)
    tab.cover_seconds.setSuffix(' 秒')
    body.addWidget(tab.cover_seconds)
    custom = QWidget()
    custom_layout = QHBoxLayout(custom)
    custom_layout.setContentsMargins(0, 0, 0, 0)
    tab.cover_file = QLineEdit()
    tab.cover_file.setPlaceholderText('JPG / PNG / WebP 图片')
    custom_layout.addWidget(tab.cover_file, 1)
    custom_layout.addWidget(button('选择图片', tab.choose_cover))
    body.addWidget(custom)
    tab.cover_button = button('获取 / 预览封面', tab.preview_cover)
    body.addWidget(tab.cover_button)
    tab.cover_preview = label('封面预览', 'muted')
    tab.cover_preview.setAlignment(Qt.AlignCenter)
    tab.cover_preview.setFixedHeight(148)
    tab.cover_preview.setStyleSheet('background: #25292e; border: 1px dashed #454f58; border-radius: 8px; color: #a4adb5;')
    body.addWidget(tab.cover_preview)
    body.addWidget(label('4:3 与 16:9 自动补边，保留完整图片。', 'muted'))
    def update_cover():
        mode = tab.cover_mode.currentData()
        tab.cover_seconds.setEnabled(mode == 'frame')
        tab.cover_seconds.setVisible(mode == 'frame')
        custom.setVisible(mode == 'custom')
    tab.cover_mode.currentIndexChanged.connect(update_cover)
    update_cover()
    left.addWidget(cover)
    left.addStretch()

    draft, body = card('标题与简介', '歌姬与署名按本次作品填写，可留空。', '03')
    tab.song, tab.voice, tab.credit = QLineEdit(), QLineEdit(), QLineEdit()
    tab.song.setPlaceholderText('歌名')
    tab.voice.setPlaceholderText('翻唱歌姬（可选）')
    tab.credit.setPlaceholderText('调音署名（可选）')
    body.addWidget(tab.song)
    row = QHBoxLayout()
    row.addWidget(tab.voice)
    row.addWidget(tab.credit)
    body.addLayout(row)
    def template():
        tab.apply_title()
        tab.append_credit()
    body.addWidget(button('应用标题格式与署名', template))
    tabs = QTabWidget()
    for platform, name in (('bilibili', 'B站'), ('xiaohongshu', '小红书')):
        panel = QWidget()
        layout = QVBoxLayout(panel)
        layout.setContentsMargins(0, 12, 0, 0)
        enabled = QCheckBox('上传到' + name)
        enabled.setChecked(True)
        layout.addWidget(enabled)
        title = QLineEdit()
        title.setPlaceholderText('【歌姬翻唱】歌名，也可自行编辑')
        layout.addWidget(title)
        description = QTextEdit()
        description.setAcceptRichText(False)
        description.setPlaceholderText('本家、歌姬与 STAFF 列表')
        description.setMinimumHeight(160)
        layout.addWidget(description)
        counter = label('', 'muted')
        layout.addWidget(counter)
        tab.fields[platform] = {'enabled': enabled, 'title': title, 'description': description, 'counter': counter}
        title.textChanged.connect(tab.count_text)
        description.textChanged.connect(tab.count_text)
        title.textChanged.connect(tab.refresh_action)
        description.textChanged.connect(tab.refresh_action)
        enabled.toggled.connect(tab.refresh_action)
        tabs.addTab(panel, name)
    body.addWidget(tabs)
    right.addWidget(draft)
    controls, body = card('平台账号与上传控制')
    for platform, name in (('bilibili', 'B站'), ('xiaohongshu', '小红书')):
        row = QHBoxLayout()
        row.addWidget(label(name), 1)
        row.addWidget(button('登录 / 更换账号', lambda checked=False, p=platform: tab.launch_browser(p, login_only=True)))
        more = QToolButton()
        more.setText('更多')
        menu = QMenu(more)
        menu.addAction('继续填写当前上传', lambda checked=False, p=platform: tab.resume_browser(p))
        menu.addAction('关闭平台任务', lambda checked=False, p=platform: tab.stop_browser(p))
        more.setMenu(menu)
        more.setPopupMode(QToolButton.InstantPopup)
        row.addWidget(more)
        body.addLayout(row)
    tab.accounts_toggle = fold('账号与上传控制', controls, right)
    right.addStretch()
    footer = QHBoxLayout()
    tab.status = label('准备就绪 · 添加成品视频与来源资料')
    footer.addWidget(tab.status, 1)
    more = QToolButton()
    more.setText('发布资料')
    menu = QMenu(more)
    menu.addAction('打开发布包目录', tab.open_bundle)
    menu.addAction('载入已有发布包', tab.choose_bundle)
    more.setMenu(menu)
    more.setPopupMode(QToolButton.InstantPopup)
    footer.addWidget(more)
    tab.prepare_button = button('生成发布资料', tab.primary_action, 'primary')
    tab.prepare_button.setMinimumWidth(156)
    footer.addWidget(tab.prepare_button)
    outer.addLayout(footer)
    tab.log = QTextEdit()
    tab.log.setReadOnly(True)
    tab.log.setAcceptRichText(False)
    tab.log.setFixedHeight(96)
    tab.log_toggle = fold('发布日志', tab.log, outer)
    for field in (tab.job, tab.video, tab.cover_file):
        field.textChanged.connect(tab.refresh_action)
    tab.cover_mode.currentIndexChanged.connect(tab.refresh_action)
    tab.cover_seconds.valueChanged.connect(tab.refresh_action)
