"""Sidebar workspace and focused processing/results pages."""
import json
from pathlib import Path
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QGridLayout, QLineEdit,
                            QTextEdit, QComboBox, QCheckBox, QProgressBar, QStackedWidget,
                            QButtonGroup, QTreeWidget, QTreeWidgetItem, QHeaderView)
from common import ROOT, app_path, load_config, output_directory, job_directories
from desktop_theme import apply_theme, button, card, fold, label, page, scroll_content
from results_ui import ResultsPage


def build_processing(window):
    panel, outer = page('处理音乐', '选择工作流预设，添加音乐后开始处理。')
    preset_row = QHBoxLayout()
    preset_row.addWidget(label('工作流预设'))
    window.workflow_preset = QComboBox()
    window.workflow_preset.setMinimumWidth(225)
    window.workflow_preset.setMaximumWidth(390)
    window.workflow_preset.setToolTip('选择已保存的工作流，流程、模型、设备和歌词设置会一起应用。')
    preset_row.addWidget(window.workflow_preset, 1)
    preset_row.addStretch()
    preset_row.addWidget(button('编辑工作流与设备', lambda: window.navigate(5)))
    outer.addLayout(preset_row)
    window.workflow_summary = label('使用当前工作流', 'muted')
    outer.addWidget(window.workflow_summary)
    content = scroll_content(outer)
    grid = QGridLayout(content)
    grid.setContentsMargins(0, 0, 0, 0)
    grid.setSpacing(24)
    grid.setColumnStretch(0, 3)
    grid.setColumnStretch(1, 2)
    left, right = QVBoxLayout(), QVBoxLayout()
    left.setSpacing(18)
    right.setSpacing(18)
    grid.addLayout(left, 0, 0)
    grid.addLayout(right, 0, 1)
    source, body = card('音乐来源', '使用 B站视频，或直接导入本地音乐。', '01')
    window.input_mode = QComboBox()
    window.input_mode.addItem('B站 BV 号 / 链接', 'bilibili')
    window.input_mode.addItem('本地音乐文件', 'local')
    body.addWidget(window.input_mode)
    window.bv_panel = QWidget()
    bv = QVBoxLayout(window.bv_panel)
    bv.setContentsMargins(0, 0, 0, 0)
    window.source = QLineEdit(load_config().get('default_source', ''))
    window.source.setPlaceholderText('粘贴 BV 号或 B站视频链接')
    bv.addWidget(window.source)
    body.addWidget(window.bv_panel)
    window.music_panel = QWidget()
    music = QHBoxLayout(window.music_panel)
    music.setContentsMargins(0, 0, 0, 0)
    window.local_music = QLineEdit()
    window.local_music.setPlaceholderText('选择或粘贴音乐文件路径')
    music.addWidget(window.local_music, 1)
    window.choose_music_btn = button('选择文件', window.choose_music)
    music.addWidget(window.choose_music_btn)
    body.addWidget(window.music_panel)
    window.input_mode.currentIndexChanged.connect(window.update_source_panel)
    window.update_source_panel()
    left.addWidget(source)

    lyrics, body = card('歌词与 MIDI', '主唱与和声独立识别，保留双轨输出。', '02')
    row = QHBoxLayout()
    row.addWidget(label('歌词语言'))
    window.language = QComboBox()
    window.language.addItem('中文', 'zh')
    window.language.addItem('日语', 'ja')
    row.addWidget(window.language)
    row.addStretch()
    body.addLayout(row)
    window.recognize = QCheckBox('识别歌词并写入 MIDI')
    window.recognize.setChecked(True)
    body.addWidget(window.recognize)
    window.zh_lyric_panel = QWidget()
    formats = QHBoxLayout(window.zh_lyric_panel)
    formats.setContentsMargins(0, 0, 0, 0)
    formats.addWidget(label('中文歌词格式'))
    window.zh_lyric_mode = QComboBox()
    window.zh_lyric_mode.addItem('汉字', 'hanzi')
    window.zh_lyric_mode.addItem('拼音', 'pinyin')
    window.zh_lyric_mode.setToolTip('选择 MIDI 歌词事件使用的文字格式，主唱和和声使用同一设置。')
    formats.addWidget(window.zh_lyric_mode, 1)
    body.addWidget(window.zh_lyric_panel)
    window.language.currentIndexChanged.connect(window.update_lyric_options)
    window.recognize.toggled.connect(window.update_lyric_options)
    window.update_lyric_options()
    reference = QWidget()
    reference_layout = QVBoxLayout(reference)
    reference_layout.setContentsMargins(0, 0, 0, 0)
    window.lyrics = QTextEdit()
    window.lyrics.setAcceptRichText(False)
    window.lyrics.setPlaceholderText('主唱歌词；只粘贴歌词，空格、标点和换行会自动去除。')
    window.lyrics.setFixedHeight(110)
    reference_layout.addWidget(window.lyrics)
    window.backing_lyrics = QLineEdit()
    window.backing_lyrics.setPlaceholderText('和声歌词（可选，留空则独立识别）')
    reference_layout.addWidget(window.backing_lyrics)
    window.lyrics_toggle = fold('参考歌词（可选）', reference, body)
    window.recognize.toggled.connect(window.lyrics.setEnabled)
    window.recognize.toggled.connect(window.backing_lyrics.setEnabled)
    left.addWidget(lyrics)
    left.addStretch()

    model, body = card('分离方案', '先分出人声与伴奏，再拆主唱和和声。', '03')
    window.voice_mode = QComboBox()
    window.voice_mode.addItem('自动分离 · 主唱 / 和声双轨', 'dual')
    window.voice_mode.addItem('导入外部分轨', 'import')
    window.voice_mode.addItem('合并人声 · 单轨 MIDI', 'single')
    body.addWidget(window.voice_mode)
    window.automatic_panel = QWidget()
    automatic = QVBoxLayout(window.automatic_panel)
    automatic.setContentsMargins(0, 0, 0, 0)
    window.separator_model = QComboBox()
    window.separator_model.addItem('Karaoke 2 · 内置', 'dual')
    window.separator_model.addItem('BS-RoFormer · 可选组件', 'roformer')
    automatic.addWidget(window.separator_model)
    window.component_status = label('', 'muted')
    automatic.addWidget(window.component_status)
    window.component_link = button('前往下载组件', lambda: window.navigate(1))
    automatic.addWidget(window.component_link)
    body.addWidget(window.automatic_panel)
    window.import_panel = QWidget()
    imports = QVBoxLayout(window.import_panel)
    imports.setContentsMargins(0, 0, 0, 0)
    imports.addWidget(label('从项目起点导出完整 WAV，保留开头静音。', 'muted'))
    for key, name in (('lead', '主唱'), ('backing', '和声'), ('instrumental', '伴奏')):
        row = QHBoxLayout()
        field = QLineEdit()
        field.setPlaceholderText(name + ' WAV')
        window.stem_fields[key] = field
        row.addWidget(field, 1)
        row.addWidget(button('选择', lambda checked=False, k=key: window.choose_stem(k)))
        imports.addLayout(row)
    body.addWidget(window.import_panel)
    window.separator_model.currentIndexChanged.connect(window.update_component_state)
    window.voice_mode.currentIndexChanged.connect(window.update_import_panel)
    right.addWidget(model)
    settings, body = card('输出与处理设置', '每个任务单独保存原视频、音频和 MIDI。', '04')
    body.addWidget(label('保存目录', 'muted'))
    window.output_panel = QWidget()
    output = QHBoxLayout(window.output_panel)
    output.setContentsMargins(0, 0, 0, 0)
    window.output_dir = QLineEdit()
    initial_directory = output_directory()
    window.output_dir.setText('jobs' if initial_directory == ROOT / 'jobs' else str(initial_directory))
    window.output_dir.setPlaceholderText('默认：助手目录 / jobs')
    window.output_dir.setToolTip('选择任务保存目录。留空时使用助手目录的 jobs 文件夹。')
    output.addWidget(window.output_dir, 1)
    window.choose_output_btn = button('选择目录', window.choose_output_directory)
    output.addWidget(window.choose_output_btn)
    body.addWidget(window.output_panel)
    window.output_summary = label('双轨 MIDI · 主唱 WAV · 和声 WAV · 伴奏 WAV', 'success')
    body.addWidget(window.output_summary)
    advanced = QWidget()
    advanced_layout = QVBoxLayout(advanced)
    advanced_layout.setContentsMargins(0, 0, 0, 0)
    window.precision = QCheckBox('精细提取 MIDI（较慢）')
    window.precision.setChecked(True)
    window.precision.setToolTip('开启使用 16 步 GAME 推理，关闭使用 8 步。')
    advanced_layout.addWidget(window.precision)
    advanced_layout.addWidget(label('新模型推理设备', 'muted'))
    window.roformer_device = QComboBox()
    window.roformer_device.addItem('自动 · CUDA 可用时优先 GPU', 'auto')
    window.roformer_device.addItem('CPU', 'cpu')
    window.roformer_device.addItem('NVIDIA GPU / CUDA', 'cuda')
    advanced_layout.addWidget(window.roformer_device)
    window.advanced_toggle = fold('高级设置', advanced, body)
    # Device and extraction precision are edited on the workflow canvas.
    window.advanced_toggle.hide()
    advanced.hide()
    right.addWidget(settings)
    right.addStretch()

    footer = QWidget()
    footer.setObjectName('footer')
    footer_layout = QVBoxLayout(footer)
    footer_layout.setContentsMargins(0, 0, 0, 0)
    row = QHBoxLayout()
    window.status = label('准备就绪 · 添加音乐后开始处理')
    row.addWidget(window.status, 1)
    window.stop = button('取消处理', window.cancel, 'danger')
    window.stop.setEnabled(False)
    window.stop.hide()
    row.addWidget(window.stop)
    window.start = button('开始处理', window.start_new, 'primary')
    window.start.setMinimumWidth(142)
    row.addWidget(window.start)
    footer_layout.addLayout(row)
    window.progress = QProgressBar()
    window.progress.setRange(0, 6)
    window.progress.setValue(0)
    window.progress.setTextVisible(False)
    window.progress.setFixedHeight(8)
    footer_layout.addWidget(window.progress)
    window.progress_detail = label('尚未开始', 'muted')
    footer_layout.addWidget(window.progress_detail)
    stage_row = QHBoxLayout()
    window.stage_labels = {}
    from progress_state import TITLES
    for key, name in TITLES.items():
        value = label(name, 'muted')
        window.stage_labels[key] = value
        stage_row.addWidget(value)
    footer_layout.addLayout(stage_row)
    window.error_panel, error_body = card('任务需要处理')
    window.error_message = label('', 'error')
    error_body.addWidget(window.error_message)
    recovery_row = QHBoxLayout()
    recovery_row.addWidget(button('继续 / 重试', window.retry_job, 'primary'))
    window.cpu_retry = button('改用 CPU 继续', window.retry_cpu)
    recovery_row.addWidget(window.cpu_retry)
    recovery_row.addWidget(button('查看日志', lambda: window.log_toggle.setChecked(True)))
    window.recovery_action = button('检查设置', window.open_recovery)
    recovery_row.addWidget(window.recovery_action)
    error_body.addLayout(recovery_row)
    footer_layout.addWidget(window.error_panel)
    window.error_panel.hide()
    window.log = QTextEdit()
    window.log.setReadOnly(True)
    window.log.setAcceptRichText(False)
    window.log.document().setMaximumBlockCount(1800)
    window.log.setFixedHeight(140)
    window.log_toggle = fold('处理日志', window.log, footer_layout)
    outer.addWidget(footer)
    return panel


def workspace_geometry(screen, offscreen=False):
    if offscreen:
        return (1600, 1000), (1000, 680)
    available = (max(1, screen.width() - 48), max(1, screen.height() - 48))
    initial = (min(1600, available[0]), min(1000, available[1]))
    minimum = (min(1000, available[0]), min(680, available[1]))
    return initial, minimum


def build_window(window):
    apply_theme(window)
    screen = QApplication.primaryScreen().availableGeometry()
    initial, minimum = workspace_geometry(screen, QApplication.platformName() == 'offscreen')
    window.setMinimumSize(*minimum)
    window.resize(*initial)
    outer = QHBoxLayout(window)
    outer.setContentsMargins(0, 0, 0, 0)
    outer.setSpacing(0)
    sidebar = QWidget()
    sidebar.setObjectName('sidebar')
    sidebar.setFixedWidth(208)
    nav = QVBoxLayout(sidebar)
    nav.setContentsMargins(14, 28, 14, 20)
    nav.setSpacing(8)
    icon = label()
    icon.setPixmap(QPixmap(str(ROOT / 'assets/app.png')).scaled(56, 56, Qt.KeepAspectRatio, Qt.SmoothTransformation))
    nav.addWidget(icon)
    brand = label('BVWA', 'heading')
    brand.setProperty('role', 'success')
    brand.setStyleSheet('font-size: 28px; font-weight: 600; color: #a7edd6;')
    nav.addWidget(brand)
    nav.addWidget(label('术力口工作流助手', 'muted'))
    nav.addSpacing(28)
    window.nav_group = QButtonGroup(window)
    titles = ('处理音乐', '模型与组件', '任务与结果', '发布准备', '设置与更新', '工作流', '缓存与磁盘', '歌词转字幕')
    window.nav_buttons = [None] * len(titles)
    for index in (0, 1, 2, 3, 5, 6, 7, 4):
        title = titles[index]
        item = button(title, lambda checked=False, i=index: window.navigate(i), 'nav')
        item.setCheckable(True)
        window.nav_group.addButton(item)
        nav.addWidget(item)
        window.nav_buttons[index] = item
    nav.addStretch()
    nav.addWidget(label('分离与 MIDI 在本地运行\n上传后由你确认发布', 'muted'))
    outer.addWidget(sidebar)
    window.pages = QStackedWidget()
    window.tabs = window.pages
    outer.addWidget(window.pages, 1)
    window.pages.addWidget(build_processing(window))
    from components_ui import ComponentsPage
    window.components = ComponentsPage(window)
    window.pages.addWidget(window.components)
    window.results = ResultsPage(window)
    window.pages.addWidget(window.results)
    from publishing_ui import PublishingTab
    window.publishing = PublishingTab(window)
    window.pages.addWidget(window.publishing)
    from updates_ui import UpdatesPage
    window.updates = UpdatesPage(window)
    window.pages.addWidget(window.updates)
    from workflow_ui import WorkflowPage
    window.workflow = WorkflowPage(window)
    window.pages.addWidget(window.workflow)
    window.workflow_preset.currentIndexChanged.connect(window.choose_processing_preset)
    from storage_ui import StoragePage
    window.storage = StoragePage(window)
    window.pages.addWidget(window.storage)
    from subtitles_ui import SubtitlesPage
    window.subtitles = SubtitlesPage(window)
    window.pages.addWidget(window.subtitles)
    for control in (window.language, window.zh_lyric_mode, window.voice_mode, window.separator_model, window.roformer_device):
        control.currentIndexChanged.connect(window.quick_options_changed)
    window.recognize.toggled.connect(window.quick_options_changed)
    window.update_import_panel()
    window.refresh_workflow_summary()
    window.navigate(0)
