"""Sidebar workspace and focused processing/results pages."""
import json
from pathlib import Path
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QGridLayout, QLineEdit,
                            QTextEdit, QComboBox, QCheckBox, QProgressBar, QStackedWidget,
                            QButtonGroup, QTreeWidget, QTreeWidgetItem, QHeaderView)
from common import ROOT, app_path, load_config
from desktop_theme import apply_theme, button, card, fold, label, page, scroll_content


class ResultsPage(QWidget):
    def __init__(self, owner):
        super().__init__()
        self.owner, self.selected_job = owner, None
        container, layout = page('任务与结果', '查看生成文件，继续未完成任务，或使用原输入重新处理。')
        outer = QVBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0)
        outer.addWidget(container)
        self.tree = QTreeWidget()
        self.tree.setHeaderLabels(['音乐 / 任务', '状态', '处理方式'])
        self.tree.setRootIsDecorated(False)
        self.tree.setAlternatingRowColors(False)
        self.tree.header().setSectionResizeMode(0, QHeaderView.Stretch)
        self.tree.itemSelectionChanged.connect(self.select)
        layout.addWidget(self.tree, 1)
        self.detail = label('暂无任务。先在“处理音乐”页面添加音乐。', 'muted')
        layout.addWidget(self.detail)
        row = QHBoxLayout()
        owner.folder = button('打开结果目录', owner.open_folder, 'primary')
        owner.resume = button('继续任务', owner.resume_last)
        owner.reprocess = button('重新分离 / MIDI', owner.reprocess_last)
        row.addWidget(owner.folder)
        row.addWidget(owner.resume)
        row.addWidget(owner.reprocess)
        row.addStretch()
        row.addWidget(button('刷新', self.reload))
        layout.addLayout(row)
        layout.addWidget(label('VOCALOID 6：通过“文件 → 导入”导入 MIDI，带歌词时选择 UTF-8。空声部不代表文件损坏。', 'muted'))
        self.reload()

    def reload(self):
        selected = self.selected_job
        self.tree.clear()
        self.selected_job = None
        jobs = ROOT / 'jobs'
        for directory in sorted(jobs.glob('*'), reverse=True) if jobs.exists() else []:
            try:
                request = json.loads((directory / 'request.json').read_text(encoding='utf-8'))
                status_file = directory / 'status.json'
                state = json.loads(status_file.read_text(encoding='utf-8')).get('state', 'ready') if status_file.exists() else 'ready'
                text = {'done': '已完成', 'completed': '已完成', 'failed': '未完成', 'running': '处理中', 'cancelled': '已取消', 'ready': '待处理'}.get(state, state)
                mode = {'dual': 'Karaoke 2 双轨', 'roformer': 'BS-RoFormer 双轨', 'import': '外部分轨', 'single': '人声单轨'}.get(request.get('voice_mode'), '人声单轨')
                item = QTreeWidgetItem([request.get('source_title') or request.get('bv') or directory.name, text, mode])
                item.setData(0, Qt.UserRole, str(directory))
                item.setData(1, Qt.UserRole, request.get('voice_mode', 'single'))
                item.setToolTip(0, directory.name)
                self.tree.addTopLevelItem(item)
                if selected == directory or (selected is None and self.owner.job == directory):
                    self.tree.setCurrentItem(item)
            except (OSError, ValueError, KeyError):
                continue
        if self.tree.topLevelItemCount() and not self.tree.selectedItems():
            self.tree.setCurrentItem(self.tree.topLevelItem(0))
        self.select()

    def select(self):
        items = self.tree.selectedItems()
        self.selected_job = Path(items[0].data(0, Qt.UserRole)) if items else None
        if self.selected_job:
            single = items[0].data(1, Qt.UserRole) == 'single'
            output = 'vocals.mid（单轨）与人声、伴奏 WAV' if single else 'voices.mid（双轨）与分轨 WAV'
            self.detail.setText('输出：' + output + ' · ' + self.selected_job.name)
        else:
            self.detail.setText('暂无任务。先在“处理音乐”页面添加音乐。')
        self.detail.setToolTip(str(self.selected_job or ''))
        active = self.owner.runner is not None and self.owner.runner.isRunning()
        self.owner.resume.setEnabled(bool(self.selected_job) and not active)
        self.owner.reprocess.setEnabled(bool(self.selected_job) and not active)
        self.owner.folder.setEnabled(bool(self.selected_job))


def build_processing(window):
    panel, outer = page('处理音乐', '添加音乐，选择分离方案，生成可调音的 MIDI。')
    content = scroll_content(outer)
    grid = QGridLayout(content)
    grid.setContentsMargins(0, 0, 0, 0)
    grid.setSpacing(18)
    grid.setColumnStretch(0, 3)
    grid.setColumnStretch(1, 2)
    left, right = QVBoxLayout(), QVBoxLayout()
    left.setSpacing(18)
    right.setSpacing(18)
    grid.addLayout(left, 0, 0)
    grid.addLayout(right, 0, 1)
    source, body = card('音乐来源', '使用 B站视频，或直接导入本地音乐。', '01')
    window.input_mode = QComboBox()
    window.input_mode.addItem('B站 BV 号 / 链接', 'bilibili')
    window.input_mode.addItem('本地音乐文件', 'local')
    body.addWidget(window.input_mode)
    window.bv_panel = QWidget()
    bv = QVBoxLayout(window.bv_panel)
    bv.setContentsMargins(0, 0, 0, 0)
    window.source = QLineEdit(load_config().get('default_source', ''))
    window.source.setPlaceholderText('粘贴 BV 号或 B站视频链接')
    bv.addWidget(window.source)
    body.addWidget(window.bv_panel)
    window.music_panel = QWidget()
    music = QHBoxLayout(window.music_panel)
    music.setContentsMargins(0, 0, 0, 0)
    window.local_music = QLineEdit()
    window.local_music.setPlaceholderText('选择或粘贴音乐文件路径')
    music.addWidget(window.local_music, 1)
    window.choose_music_btn = button('选择文件', window.choose_music)
    music.addWidget(window.choose_music_btn)
    body.addWidget(window.music_panel)
    window.input_mode.currentIndexChanged.connect(window.update_source_panel)
    window.update_source_panel()
    left.addWidget(source)

    lyrics, body = card('歌词与 MIDI', '主唱与和声独立识别，保留双轨输出。', '02')
    row = QHBoxLayout()
    row.addWidget(label('歌词语言'))
    window.language = QComboBox()
    window.language.addItem('中文', 'zh')
    window.language.addItem('日语', 'ja')
    row.addWidget(window.language)
    row.addStretch()
    body.addLayout(row)
    window.recognize = QCheckBox('识别歌词并写入 MIDI')
    window.recognize.setChecked(True)
    body.addWidget(window.recognize)
    reference = QWidget()
    reference_layout = QVBoxLayout(reference)
    reference_layout.setContentsMargins(0, 0, 0, 0)
    window.lyrics = QTextEdit()
    window.lyrics.setAcceptRichText(False)
    window.lyrics.setPlaceholderText('主唱歌词；只粘贴歌词，空格、标点和换行会自动去除。')
    window.lyrics.setFixedHeight(110)
    reference_layout.addWidget(window.lyrics)
    window.backing_lyrics = QLineEdit()
    window.backing_lyrics.setPlaceholderText('和声歌词（可选，留空则独立识别）')
    reference_layout.addWidget(window.backing_lyrics)
    window.lyrics_toggle = fold('参考歌词（可选）', reference, body)
    window.recognize.toggled.connect(window.lyrics.setEnabled)
    window.recognize.toggled.connect(window.backing_lyrics.setEnabled)
    left.addWidget(lyrics)
    left.addStretch()

    model, body = card('分离方案', '先分出人声与伴奏，再拆主唱和和声。', '03')
    window.voice_mode = QComboBox()
    window.voice_mode.addItem('自动分离 · 主唱 / 和声双轨', 'dual')
    window.voice_mode.addItem('导入外部分轨', 'import')
    window.voice_mode.addItem('合并人声 · 单轨 MIDI', 'single')
    body.addWidget(window.voice_mode)
    window.automatic_panel = QWidget()
    automatic = QVBoxLayout(window.automatic_panel)
    automatic.setContentsMargins(0, 0, 0, 0)
    window.separator_model = QComboBox()
    window.separator_model.addItem('Karaoke 2 · 内置', 'dual')
    window.separator_model.addItem('BS-RoFormer · 可选组件', 'roformer')
    automatic.addWidget(window.separator_model)
    window.component_status = label('', 'muted')
    automatic.addWidget(window.component_status)
    window.component_link = button('前往下载组件', lambda: window.navigate(1))
    automatic.addWidget(window.component_link)
    body.addWidget(window.automatic_panel)
    window.import_panel = QWidget()
    imports = QVBoxLayout(window.import_panel)
    imports.setContentsMargins(0, 0, 0, 0)
    imports.addWidget(label('从项目起点导出完整 WAV，保留开头静音。', 'muted'))
    for key, name in (('lead', '主唱'), ('backing', '和声'), ('instrumental', '伴奏')):
        row = QHBoxLayout()
        field = QLineEdit()
        field.setPlaceholderText(name + ' WAV')
        window.stem_fields[key] = field
        row.addWidget(field, 1)
        row.addWidget(button('选择', lambda checked=False, k=key: window.choose_stem(k)))
        imports.addLayout(row)
    body.addWidget(window.import_panel)
    window.separator_model.currentIndexChanged.connect(window.update_component_state)
    window.voice_mode.currentIndexChanged.connect(window.update_import_panel)
    right.addWidget(model)
    settings, body = card('输出与处理设置', '文件自动保存至助手目录的 jobs 文件夹。', '04')
    window.output_summary = label('双轨 MIDI · 主唱 WAV · 和声 WAV · 伴奏 WAV', 'success')
    body.addWidget(window.output_summary)
    advanced = QWidget()
    advanced_layout = QVBoxLayout(advanced)
    advanced_layout.setContentsMargins(0, 0, 0, 0)
    window.precision = QCheckBox('精细提取 MIDI（较慢）')
    window.precision.setChecked(True)
    window.precision.setToolTip('开启使用 16 步 GAME 推理，关闭使用 8 步。')
    advanced_layout.addWidget(window.precision)
    advanced_layout.addWidget(label('新模型推理设备', 'muted'))
    window.roformer_device = QComboBox()
    window.roformer_device.addItem('自动 · CUDA 可用时优先 GPU', 'auto')
    window.roformer_device.addItem('CPU', 'cpu')
    window.roformer_device.addItem('NVIDIA GPU / CUDA', 'cuda')
    advanced_layout.addWidget(window.roformer_device)
    window.advanced_toggle = fold('高级设置', advanced, body)
    right.addWidget(settings)
    right.addStretch()

    footer = QWidget()
    footer.setObjectName('footer')
    footer_layout = QVBoxLayout(footer)
    footer_layout.setContentsMargins(0, 0, 0, 0)
    row = QHBoxLayout()
    window.status = label('准备就绪 · 添加音乐后开始处理')
    row.addWidget(window.status, 1)
    window.stop = button('取消处理', window.cancel, 'danger')
    window.stop.setEnabled(False)
    window.stop.hide()
    row.addWidget(window.stop)
    window.start = button('开始处理', window.start_new, 'primary')
    window.start.setMinimumWidth(142)
    row.addWidget(window.start)
    footer_layout.addLayout(row)
    window.progress = QProgressBar()
    window.progress.setRange(0, 6)
    window.progress.setValue(0)
    window.progress.setTextVisible(False)
    window.progress.setFixedHeight(8)
    footer_layout.addWidget(window.progress)
    window.log = QTextEdit()
    window.log.setReadOnly(True)
    window.log.setAcceptRichText(False)
    window.log.document().setMaximumBlockCount(1800)
    window.log.setFixedHeight(140)
    window.log_toggle = fold('处理日志', window.log, footer_layout)
    outer.addWidget(footer)
    return panel


def build_window(window):
    apply_theme(window)
    window.resize(1220, 820)
    window.setMinimumSize(980, 680)
    outer = QHBoxLayout(window)
    outer.setContentsMargins(0, 0, 0, 0)
    outer.setSpacing(0)
    sidebar = QWidget()
    sidebar.setObjectName('sidebar')
    sidebar.setFixedWidth(180)
    nav = QVBoxLayout(sidebar)
    nav.setContentsMargins(14, 28, 14, 20)
    nav.setSpacing(8)
    brand = label('BVWA', 'heading')
    brand.setProperty('role', 'success')
    brand.setStyleSheet('font-size: 25px; font-weight: 600; color: #8fd6bd;')
    nav.addWidget(brand)
    nav.addWidget(label('音乐工作流助手', 'muted'))
    nav.addSpacing(28)
    window.nav_group = QButtonGroup(window)
    window.nav_buttons = []
    for index, title in enumerate(('处理音乐', '模型与组件', '任务与结果', '发布准备')):
        item = button(title, lambda checked=False, i=index: window.navigate(i), 'nav')
        item.setCheckable(True)
        window.nav_group.addButton(item)
        nav.addWidget(item)
        window.nav_buttons.append(item)
    nav.addStretch()
    nav.addWidget(label('分离与 MIDI 在本地运行\n上传后由你确认发布', 'muted'))
    outer.addWidget(sidebar)
    window.pages = QStackedWidget()
    window.tabs = window.pages
    outer.addWidget(window.pages, 1)
    window.pages.addWidget(build_processing(window))
    from components_ui import ComponentsPage
    window.components = ComponentsPage(window)
    window.pages.addWidget(window.components)
    window.results = ResultsPage(window)
    window.pages.addWidget(window.results)
    from publishing_ui import PublishingTab
    window.publishing = PublishingTab(window)
    window.pages.addWidget(window.publishing)
    window.update_import_panel()
    window.navigate(0)
