"""Audit/prune the release inventory only; installed runtime files are never deleted."""
import argparse
import collections
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPARE_HFA = 'dependencies/vocal2midi/experiments/1218_hfa_model_new_dict/model-simplify.onnx'
PYTHON = 'dependencies/vocal2midi/python/'
QT = PYTHON+'Lib/site-packages/PyQt5/Qt5/'


def exclusion(name):
    """Deliberately narrow rules; active ASR/pitch/alignment weights stay unchanged."""
    if Path(name).name.lower().startswith(('license', 'copying', 'notice')):
        return None
    if name == SPARE_HFA:
        return 'Unused alternate HFA export; inference explicitly opens model.onnx'
    if name.startswith(QT+'qml/'):
        return 'Qt Quick resources; the assistant uses Qt Widgets'
    if name == PYTHON+'get-pip.py' or name.startswith(PYTHON+'Lib/site-packages/pip/'):
        return 'Development installer; portable restoration and components do not use pip'
    if name.startswith(PYTHON) and any(p in ('tests', 'test', '__pycache__') for p in name.split('/')):
        return 'Third-party test fixtures or generated bytecode'
    return None


def audit(manifest):
    retained, removed = [], []
    for entry in manifest['entries']:
        reason = exclusion(entry['file'])
        (removed if reason else retained).append({**entry, **({'reason': reason} if reason else {})})
    return retained, removed


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--apply', action='store_true', help='Update inventory only, without producing an archive')
    args = parser.parse_args()
    path = ROOT/'dependencies/manifest.json'
    original = json.loads(path.read_text(encoding='utf-8'))
    retained, removed = audit(original)
    groups = collections.Counter()
    for entry in removed:
        groups[entry['reason']] += entry['bytes']
    report = {'original_files': len(original['entries']), 'retained_files': len(retained),
              'original_bytes': sum(e['bytes'] for e in original['entries']),
              'retained_bytes': sum(e['bytes'] for e in retained),
              'removed_bytes': sum(e['bytes'] for e in removed), 'categories': dict(groups), 'excluded': removed,
              'scope': 'Release inventory only; installed files and active model weights are unchanged.'}
    folder = ROOT/'work/test-results'
    folder.mkdir(parents=True, exist_ok=True)
    (folder/'package-optimization.json').write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
    if args.apply and removed:
        backup = ROOT/'work/dependency-manifest-before-optimization.json'
        if not backup.exists():
            backup.write_bytes(path.read_bytes())
        manifest = dict(original, entries=retained, files=len(retained), bytes=report['retained_bytes'])
        path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2)+'\n', encoding='utf-8', newline='\n')
    print(json.dumps({k:v for k,v in report.items() if k != 'excluded'}, indent=2))


if __name__ == '__main__':
    main()
